FROM mcr.microsoft.com/powershell:7.4-alpine-3.17
WORKDIR /app
SHELL [ "pwsh", "-NoLogo", "-NoProfile", "-Command" ]
RUN Install-Module pode -Scope AllUsers -Force
ENTRYPOINT [ "pwsh", "-c", "pode" ]
CMD [ "start" ]
EXPOSE 80