site_name: JoshooaJ
site_url: https://www.joshooaj.com/
site_description: "The personal blog of Josh Hendricks."
site_dir: Output/
repo_name: joshooaj/joshooaj.github.io
repo_url: https://github.com/joshooaj/joshooaj.github.io
edit_uri: edit/main/docs/
docs_dir: docs
copyright: '<label for="last-track">🎧</label><span id="last-track" class="last-track">loading...</span><br />Copyright &copy; 2021-2022 Joshua Hendricks. All rights reserved.'

nav:
  - index.md
  - Blog:
    - blog/index.md
  - MilestonePSTools: https://www.milestonepstools.com
  - PSPushover: https://www.joshooaj.com/PSPushover/
  - BGProcess: https://www.joshooaj.com/BGProcess/
  - Docs Workshop: https://www.joshooaj.com/docs-workshop/
  - Buy Me a Coffee ☕️: https://www.buymeacoffee.com/joshooaj

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/images/joshooaj.png
  features:
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - navigation.indexes

plugins:
  - search
  - tags
  - meta
  - blog:
      draft_on_serve: true
      post_excerpt: required
      blog_toc: true
      archive: true
      categories: true
      pagination: true
  - rss:
      image: https://www.joshooaj.com/assets/images/joshooaj.png
      match_path: blog/posts/.*
      abstract_delimiter: <!-- more -->
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date.created"
        default_timezone: America/Los_Angeles
      categories:
        - categories
        - tags
  - social:
      cards_layout_options:
        font_family: Open Sans
        color: "#ffffff"
        background_color: "#224cdd"
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - optimize

extra:
  social:
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
      name: RSS Feed
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/joshooaj.com
      name: Josh on Bluesky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joshooaj
      name: Josh on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/joshooaj
      name: Josh on GitHub
    - icon: fontawesome/brands/signal-messenger
      link: https://signal.me/#eu/c5pIBhxkru1zWIr6GP2vZkD3teusXme0pqCz3y9hALDfm8SRdPJC8LTkb4B846Rx
      name: Contact me on Signal

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
      - docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - def_list
  - md_in_html

extra_javascript:
  - "scripts/lasttrack.js"