name: ci
on:
  push:
    branches:
      - main
jobs:
  Publish:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    env:
      GHCR_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Publish to GH-Pages
        shell: pwsh
        run: .\build.ps1 -Task Publish
