name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./build.ps1 -Task Deploy -Token ${GH_TOKEN}
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 
